### ISSUE TITLE
Centre building meshes

### ISSUE THREAD

**Issue by s0600204** [0ADMods/aristeia#19]
The `stables` and `market` buildings are off-centre in game. (The left and right buildings in below image)

![Buildings off-centre](http://i.imgur.com/KkdvJDU.png)

To correct, these meshes must be opened in Blender, centred, then re-exported into 0AD.

> ~~In object mode, press Ctrl + A and choose what to "Apply". This will set the center to the center of the model (and not the center of the start of the model) etc. - feneur~~

They're the worst, but the `mill` and both `palace`s could do with re-centreing as well. Heck, if someone feels up to it, go through the meshes used by every building in the mod and re-centre all of them to make sure.

**Comment by niektb** [comment]
That 'Apply' option sets the origin of the mesh to the Blender mesh and doesn't remove an offset in itself. You use it after recentering the mesh properly (manually or maybe there is some automated option).

**Comment by s0600204** [comment]
I was just quoting what feneur said on the forums, and I don't really know how to use Blender.

How about this: (derived from messing around, and seems to work)
* Import `*.dae` file into Blender
* Select Object
* From the "Tool Shelf", choose "Set Origin" > "Origin to Geometry", making sure that it uses the "Bounds Center"
* Open "Properties", and set the "x" and "y" variables to 0.
* Fix rotation if necessary.
* Export to `*.dae` and test in Atlas

**Comment by StanleySweet** [comment]
That's the correct way to do it. Not sure if the only one, but that's what I would do.

**Comment by s0600204** [comment]
![Updated](http://i.imgur.com/Y48ko7al.jpg)
Better, no?

And thanks, Stan.

**Comment by StanleySweet** [comment]
Perfect :)
