### ISSUE TITLE
New release for Alpha 23 or 24

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/aristeia#25]
Will there be a new release of Aristeia for Alpha 23 or 24?

**Comment by tomasmatys** [comment]
@Jeeppler  well I am updating it for 0.23 but only so that it could be played but without any new content since I am no artist.

**Comment by Jeeppler** [comment]
Perfect. I absolutely want to play Aristeia, even if it is in a alpha or beta state.

**Comment by StanleySweet** [comment]
A version is on modio

**Comment by tomasmatys** [comment]
https://0ad.mod.io/aristeia
