### ISSUE TITLE
Are weapons and tools units (movable/trainable) or structures (static/'Found no free space to spawn trained units.')?

### ISSUE THREAD

**Issue by faerietree** [0ADMods/aristeia#5]
As weapons are basically movable (e.g. can be tied to a horse and pulled away), they should be units.

Another reason for making them units is that UnitMotion could still be either made really big (to create the impression of instant garrisoning). Or to make it zero (0) to simulate that it is dead material.

Wind could also move weapons or tools as well as physics while static structures (read: buildings) are usually tied to the ground as fix as possible.

Yet another reason is that buildings currently can't spawn other static entities (structures) but only units due to ProductionQueue's pos.y < 0 condition which leads to the "Found not enough free space to spawn trained units." GUI notification.

When weapons and tools et alia are made units, then an order is needed to make entities  pick up a garrison. This must trigger the clicked entitiy (e.g. a sword) to switch its UnitAI state to INDIVIDUAL.GARRISONING.

The unit must be in GarrisonHolder's pickup range to allow the unmanoevrable weapon/tool to garrison inside/being picked-up without having to move.

**Comment by s0600204** [comment]
Do you mind if I ask what the original thinking was behind weapons/tools? Is there a forum post, a design proposal, or specification explaining? Something to clarify what exactly is the intended end result? Just for reference purposes, if nothing else.

**Comment by s0600204** [comment]
I'm still curious to know. Regardless, we have moved in a different direction causing this issue to no longer be applicable.
