### ISSUE TITLE
Bringing the master branch back to a playable state

### ISSUE THREAD

**Issue by s0600204** [0ADMods/aristeia#7]
It has been observed both on IRC and on the Wildfire Forums that Aristeia is currently 'broken' and/or unplayable. To resolve this, the following changes have been proposed:
- [x] Mark current state with its own branch/tag
- [x] Remove weapon templates
- [x] Remove garrison-able horse template
- [x] Remove additional unit ranks
- [x] Remove promotion techs
- [x] Rename templates to restore the `_b` suffix
- [x] Reinstate 0ad-style art folder layout
- [x] Remove Unit conversion code into its own branch, then update/tweak it (the latter of which will be covered under a different issue)
- [x] Change entities referenced in included map files

Yes, this reverts a lot of changes made by primarily one person. My apologies to him for that.

From conversations I have had, I get the impression that the current unplayable state is down to people committing their own personal changes and preferences to master without checking it by anyone else first. There is this idea of a "council of modders", but in a true "council" scenario, one person would *propose* a change, and a second person would *second* the change.

**Comment by s0600204** [comment]
As of this point in time, the `devel` branch in my fork is playable in a skirmish inside 0AD.

The promotion-via-tech approach doesn't seem to have been applied to egyptian units, and the assyrian ones need having a look at anyway (in a separate issue, I think) as Atlas is telling me the XML is not validating for many of them.

**Comment by niektb** [comment]
I second these changes. Thanks for working on this!

A small thingy you might have overlooked: there are units placed on scenario maps with the wrong template names. Look in the xml-files here: https://github.com/s0600204/aristeia/tree/devel/maps/scenarios

I will look to the other changes as soon as I have time!

**Comment by s0600204** [comment]
I noticed I missed something in restoring the `_b` suffixes, corrected the appropriate commit, and then rebased, hence the repeated "s0600204 referenced this issue...' messages.

**Comment by faerietree** [comment]
True words. If the Git knowledge of mainly one person (my humble self) had been of higher degree, then this may become a real council. Definitely too much emotion has been put into this by one person, that hereby apologizes for that.
